version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 14
    on-failure: ABORT
    commands:
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - |
        if [[ ($GITHUB_EVENT_NAME == "pull_request") ]]; then 
          echo "do some test or lint check here!"
        fi
  build:
    on-failure: ABORT
    commands:
      - |
        if [[ ($GITHUB_EVENT_NAME == "push") ]]; then 
          npm run build
        fi
  post_build:
    on-failure: ABORT
    commands:
      - |
        if [[ ($GITHUB_EVENT_NAME == "push") ]]; then 
          echo "do dome post build stuff with push event"
        elif [[ ($GITHUB_EVENT_NAME == "pull_request") ]]; then 
          echo "do dome post build stuff with pull request event"
        fi

cache:
  paths:
    - node_modules/**/*
