version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 16
    on-failure: ABORT
    commands:
      - npm install
  build:
    on-failure: ABORT
    commands:
      - npm run build
  post_build:
    on-failure: ABORT
    commands:
      - aws s3 cp public s3://${DEPLOY_S3_ARN}  --recursive

cache:
  paths:
    - node_modules/**/*
