export const PER_COL_CUBE_NUM = 10;

export const PER_ROW_CUBE_NUM = 40;

export const BUFFER_ZONE_ROW_START = 0;

export const BUFFER_ZONE_ROW_END = 19;

export const DISPLAY_ZONE_ROW_START = 20;

export const DISPLAY_ZONE_ROW_END = 39;

export const TOTAL_LEVEL = 15;

export enum MATRIX_PHASE {
  TETRIMINO_FALLING = "TETRIMINO_FALLING",
  CHECK_IS_ROW_FILLED = "CHECK_IS_ROW_FILLED",
  CHECK_IS_ROW_EMPTY = "CHECK_IS_ROW_EMPTY",
}
